
os:
  - osx
  - linux

# use container-based infrastructure on Travis
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
#sudo: false

# use VM infrastructure on Travis
# exit code 137 indicates that your build is now taking more memory
# or rather it's running alongside other builds requiring a lot of memory.
# This can happen because your builds are running on container-based infrastructure and they will share the host's 4 GB memory.
# To mitigate this situation, run your builds on our sudo-enabled Precise infrastructure.
# Over there, your builds will run on a fully independent VM with 7.5 GB of (unshared) memory.
sudo: required

language: python

python:
#  - "2.7"
  - "3.5"

env:
  global:
    - TEST_ALL=1

# Using xvfb to Run Tests That Require a GUI
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
# https://github.com/travis-ci/travis-ci/issues/7313#issuecomment-279914149
before_script:
  - [[ "${TRAVIS_OS_NAME}" = "linux"  ]] && "export DISPLAY=:99.0" && "sh -e /etc/init.d/xvfb start" && sleep 3 # give xvfb some time to start
  - [[ "${TRAVIS_OS_NAME}" = "osx" ]] && ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )&

script: 
  - travis_wait 30 ./install-CGAT-tools.sh --travis

